[profile.default]
libs = ["lib"]
out = "out"
remappings = ["@opensezppling/=lib/openzeppelin-contracts/"]
src = "src"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
